### ISSUE TITLE
Take Spans From AWS Kinesis And Put in AWS XRAY 

### ISSUE THREAD

**Issue by jhonatanforero** [openzipkin/zipkin-aws#109]
Hi,
This Issue is more a Question:

My app sends data to kinesis with sender-kinesis (zipkin-aws) utility, I'm using kinesis collector for elasticsearch storage as an independent process, now I want a Hybrid--> run another kinesis collector with xray storage.

The reason for the hybrid is because I want still keep using zipkin UI for traces and AWS XRAY console for other purposes.

I don't see the kinesis collector with xray storage, does it exist? if it exists , how can I do it?

**Comment by adriancole** [comment]
Hi there. These features can be used together. For example, our docker image includes kinesis and xray so you can certainly plumb what you are looking for https://github.com/openzipkin/docker-zipkin-aws/blob/master/Dockerfile#L36
