### ISSUE TITLE
AWS Propagation Incompatible with Brave 5.6

### ISSUE THREAD

**Issue by pettyjamesm** [openzipkin/zipkin-aws#118]
Changes in https://github.com/openzipkin/brave/pull/846 made `HexCodec.writeHexByte` package-private and therefore no longer accessible from `AWSPropagation`. It also added more efficient access to string span / trace id values which should probably be used to benefit from the cached id string values.

**Comment by adriancole** [comment]
good catch. we do try to make comments when we add things to internal types
for external dependencies. in this case might be best to copy the old class
into a internal or package protected type here.

in any case it should have been shaded.. apologies!

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-aws/pull/119 sorry about this!

**Comment by pettyjamesm** [comment]
Not a problem at, glad the fix is as easy as shading- I didn’t want to try to fiddle with replacing the whole structure of the logic to use the cached string values.

**Comment by adriancole** [comment]
0.15.2 on the way
