### ISSUE TITLE
AwsClientTracing: Null pointer exception thrown for AwsAsyncClientBuilders

### ISSUE THREAD

**Issue by sdavids13** [openzipkin/zipkin-aws#121]
Stack trace includes:
```
Caused by: java.lang.NullPointerException: null
	at brave.instrumentation.aws.AwsClientTracing$TracingExecutorFactory.<init>(AwsClientTracing.java:69)
	at brave.instrumentation.aws.AwsClientTracing.build(AwsClientTracing.java:47)
```

This is because the `getClientConfiguration()` does not get initialized by default in the default builder (thus blows up when calling `clientConfiguration.getMaxConnections()` in `TracingExecutorFactory`), instead Amazon uses `AwsSyncClientParams` to provide defaults if any are missing right before they call the build method:

```
    @Override
    public final TypeToBuild build() {
        return configureMutableProperties(build(getSyncClientParams()));
    }
```

Temporary work-around: Have async builders include: `.withClientConfiguration(new ClientConfigurationFactory().getConfig());`

**Comment by devinsba** [comment]
Pushed out in `0.15.4` thanks for the report
