### ISSUE TITLE
auto-confiure not signing zipkin requests , getting blocked when storing in elasticsearh aws

### ISSUE THREAD

**Issue by hari1892** [openzipkin/zipkin-aws#144]
I have configured 2 apps which are traced by zipkin, data is stored in aws elasticsearch, if i give full acess , and also if i allow not to sign for IAM users,  zipkins data is stored in aws ES, but if i restrict for specific IAM user and try to save it in ES, am unable to store data, i was using aws autoconfiure aws-elasticsearch module, which take care of signing requests from zipkins to ES, but it is failing, however if i tried make a manual signed request to ES, it is working, is there any issue with autosigner? , pls help

**Comment by hari1892** [comment]
also, if i start zipkin with ato configure aws-elasticsearch jar file , as per documentation , when i start with parameters ES_AWS_DOMAIN  and ES_AWS_REGION , it should automatically lookup the domain name, but is not happening,  which indicates, during run time it is not picking up the configurations

am getting below error:
{
  "status" : "DOWN",
  "zipkin" : {
    "status" : "DOWN",
    "details" : {
      "ElasticsearchStorage{initialEndpoints=aws://ap-south-1/publices, index=zipkin}" : {
        "status" : "DOWN",
        "details" : {
          "error" : "java.lang.RuntimeException: couldn't lookup AWS ES domain endpoint: zipkin.autoconfigure.storage.elasticsearch.aws.AWSSignatureVersion4.delegate()Lcom/linecorp/armeria/client/Client;"
        }
      }
    }
  }

**Comment by devinsba** [comment]
Hi, it looks like you are building a custom zipkin server. Unfortunately we cannot provide support for custom servers, we are a small group of volunteers and custom servers can have so many variables that it is too big of a burden on our community.

Did you know there are pre-built distributions of zipkin? Please check out our documentation for more information: https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md
