### ISSUE TITLE
Properly address encoding and limits in SQS

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-aws#15]
If you look deeply into the code, you'll notice Amazon's SQS client uses Base64 to encode messages, similarly to how we do in Scribe. Even json has encoding issues. For example, there are constraints on which unicode characters are permitted. After all that.. there's either URL or POST encoding!

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-limits.html

Because zipkin doesn't put constraints on UTF-8, a user can create a message that cannot be published (without encoding). One way to solve this is to only permit thrift, and then always Base64 (which is fine albeit inefficient). Another way is to blindly try for json, and assume users won't use restricted unicode characters.

Either way, we have to reflect (base64) encoding overhead in `Sender.messageSizeInBytes`, and note in docs any constraints beyond that and what people should expect. (even if the answer is just watch for dropped messages).

**Comment by adriancole** [comment]
@llinder @devinsba FWIW I think we should just do one encoding with this transport: base64(thrift)
reason is that then we don't have to worry about UTF-8 limitations or other concerns where we can't store a span that was created.

We also don't need to add message properties as there's only one encoding (the default one). The size function becomes quite simple (particularly as we are adding no message properties).

```java
listSize = Encoding.THRIFT.listSizeInBytes(encodedSpans)
base64Size = (listSize + 2) * 4 / 3;
```

I'm happy to address this, if you like.

**Comment by llinder** [comment]
Agreed.  As you pointed out, using the binary attribute isn't really providing any value.  Keeping things simple and just using base64(thrift) as the message body is fine by me.

I can take this on and should be able to get something out today.

**Comment by devinsba** [comment]
Agreed here also, the advantage I saw was the transformation amazon was doing for us, but if its just Base64, well, thats what I had started writing on my own before seeing @llinder s implementation

**Comment by adriancole** [comment]
Thanks for feedback and work folks. Yeah it isn't obvious that binary just
means Base64 somewhere in the depths :)
