### ISSUE TITLE
Request signature doesn't match error connecting to Elasticsearch

### ISSUE THREAD

**Issue by jamiegs** [openzipkin/zipkin-aws#152]
I'm trying to use the `openzipkin/zipkin-aws` image with the elasticsearch storage module. 

However I'm getting the error 
```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```
within
```
zipkin.module.storage.elasticsearch.aws.ElasticsearchDomainEndpoint.get(ElasticsearchDomainEndpoint.java:76) ~[elasticsearch-aws/:?]
```

I thought at first it might just be a permissions issue of not having the correct policies but I've tried it running both on an ECS server, which had least privilege aws policies and from my computer with pretty wide open policies and I've gotten the same error.

I've tried Elasticsearch 6.8 and 7.1 and both received the same error.

I'm using the `STORAGE_TYPE=elasticsearch  and ES_AWS_DOMAIN=<my es domain name>`.  Is there something I'm missing?

**Comment by Leinad0033** [comment]
Had the same issue. We worked around it by putting our ES domain endpoint in the ES_HOSTS variable instead of using the ES_AWS_DOMAIN.

https://github.com/openzipkin/zipkin-aws/tree/master/module/storage-elasticsearch-aws

**Comment by adriancole** [comment]
thanks for the notes. will try on own on next round here.
