### ISSUE TITLE
Amazon Kinesis

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-aws#16]
Amazon Kinesis is a service similar to Kafka. It suggests lower message costs and higher amount of data per message (1MB just like Kafka). It persists all data for minimum 24hrs which means you have to pay certain costs to keep the stream alive.

I've not heard anyone request this specifically, just noting some things as we go along.

**Comment by devinsba** [comment]
- [ ] Collector #33 
- [ ] Spark Stream Factory #34 
- [ ] Reporter ???
