### ISSUE TITLE
java.lang.IllegalStateException: Missing: traceId with AWS propagation type within AWSExtractor

### ISSUE THREAD

**Issue by BenitoVisone** [openzipkin/zipkin-aws#201]
## Describe the Bug

Environment setup:

- **JDK:** Java 11.0.17
- **Spring Boot:** 2.7.13
- **Spring Cloud:** 2021.0.8
- **Spring Cloud Starter Sleuth**: 3.1.9
- **Brave**: 5.13.9
- **Zipkin-aws**: 0.21.3

In our application we use Spring Cloud Sleuth for tracing in our micro-services. We set propagation type to AWS because our architecture is based on this Cloud Provider. 

The problem we are facing is the following: When we receive an `X-Amzn-Trace-Id` header with the following format: `Root=1-1373cbb-37f4b48ed7ff3eebbd62b5e01` the application crashes with the Exception `java.lang.IllegalStateException: Missing: traceId` from the `brave.propagation` package during the trace id extraction. 

We [opened an issue on spring-cloud-sleuth](https://github.com/spring-cloud/spring-cloud-sleuth/issues/2303) which directed us here.

Based on this [AWS Documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sendingdata.html), the `X-Amzn-Trace-Id` header consists of [three numbers separated by hyphens](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sendingdata.html#:~:text=A%20trace_id%20consists%20of%20three%20numbers%20separated%20by%20hyphens.%20For%20example%2C%201%2D58406520%2Da006649127e371903a2de979.%20This%20includes%3A) *`version-time-id` ,* where the *****time***** field should be of 8 hexadecimal digits.

The problem seems related to the *time*(`1373cbb`, 7 characters) format, when its length is different from 8. In fact, in this [section of code](https://github.com/openzipkin/zipkin-aws/blob/9bb5725f20f04e09efd626cebd039213820ca47b/brave-propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java#L118) we can see that if the timestamp length is different from 8 the traceId is never initialised, causing the Exception. 

This is the only case that throws this unhandled Exception, in other cases, such as invalid hexadecimal digits, the application correctly generates a new trace id without propagating the malformed one.

Is this working as intended?

## Steps to Reproduce
In order to test this behaviour you need to test a request with the header `X-Amzn-Trace-Id: Root=1-1373cbb-37f4b48ed7ff3eebbd62b5e01` which cause the Exception being thrown.

## Expected Behaviour
The expected behaviour should be the same as when an invalid trace id with non-hexadecimal characters arrives, that is, it should be ignored and generated from scratch.

**Comment by devinsba** [comment]
Do you know the source of these headers that have only 7 hex digits for the time? Given that it's epoch time, the example above is from August 1970 which definitely isn't right.

The extractor should be more resilient but the source should also be fixed

**Comment by BenitoVisone** [comment]
We are investigating on the source of these headers trying to understand why the epoch time isn't right. 

Absolutely, the source needs to be fixed as well.

**Comment by codefromthecrypt** [comment]
thanks for the fixes in #203
