### ISSUE TITLE
Different behavior during parsing of incorrect timestamp field in AWS TraceId

### ISSUE THREAD

**Issue by GiuMontesano** [openzipkin/zipkin-aws#202]
## Environment setup:

- **JDK: Java**:  11.0.17
- **Spring Boot**: 2.7.13
- **Spring Cloud**: 2021.0.8
- **Spring Cloud Starter Sleuth**: 3.1.9
- **Brave**: 5.13.9
- **Zipkin-aws**: 0.21.3

## Describe the Bug
I found a different behavior when an incorrect timestamp field of AWS X-Amzn-Trace-Id header is parsed.

### Behavior 1
Considering this incorrect TraceId: `Root=1-z1373bbc-f1f4b48ef7ff3eebd62b5e01` (please note the leading **z** in the timestamp part of the TraceId, that is not a valid hexadecimal character).
In this case the application does not throw any Exception, but it generates a new TraceId from scratch.

###  Behavior 2
Considering this second incorrect TraceId: `Root=1-1z373bbc-f1f4b48ef7ff3eebd62b5e01` (please note the  **z**  in the second position of the timestamp part of the TraceId, that is not a valid hexadecimal character).
In this case the application throws an `java.lang.IllegalStateException: Missing: traceId`.

## Expected Behaviour
I expect the result of the first behavior in either cases (so, a new generated TraceId).

### Behavior 1
1. In order to test this behaviour you need to pass a request with following header: `X-Amzn-Trace-Id: Root=1-z1373bbc-f1f4b48ef7ff3eebd62b5e01`.
2. In this case you can notice that a new TraceId is generated.

### Behavior 2
1. In order to test this behaviour you need to pass a request with following header: `X-Amzn-Trace-Id: Root=1-1z373bbc-f1f4b48ef7ff3eebd62b5e01`.
2. In this case you can notice that a `java.lang.IllegalStateException: Missing: traceId` is thrown.

## Notes
I think that this different behaviors is originated from this [section of code](https://github.com/openzipkin/zipkin-aws/blob/9bb5725f20f04e09efd626cebd039213820ca47b/brave-propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java#L117C1-L128C14).

#### Behavior 1
The first character is not hexadecimal, so the `traceIdHigh` ([line 121](https://github.com/openzipkin/zipkin-aws/blob/9bb5725f20f04e09efd626cebd039213820ca47b/brave-propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java#L121))  variable does not contain any value and the program goes direct to last else ([line 126](https://github.com/openzipkin/zipkin-aws/blob/9bb5725f20f04e09efd626cebd039213820ca47b/brave-propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java#L126)) of the section that make a `break` from the outer loop.
When the program reaches the [line 176](https://github.com/openzipkin/zipkin-aws/blob/9bb5725f20f04e09efd626cebd039213820ca47b/brave-propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java#L176) it goes to the positive branch of the `if`, and generates a new TraceId.

#### Behavior 2
The first character is hexadecimal, so the `traceIdHigh` is initialised from this character. However the second one is not hexadecimal, so the program goes in the same [else](https://github.com/openzipkin/zipkin-aws/blob/9bb5725f20f04e09efd626cebd039213820ca47b/brave-propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java#L126) of behavior 1, that make a `break` from the outer loop.
When the program reaches the  [line 176](https://github.com/openzipkin/zipkin-aws/blob/9bb5725f20f04e09efd626cebd039213820ca47b/brave-propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java#L176)  it goes into the negative branch of the `if`, in the [line 185](https://github.com/openzipkin/zipkin-aws/blob/9bb5725f20f04e09efd626cebd039213820ca47b/brave-propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java#L185).  This  line of code generates an `java.lang.IllegalStateException` caused by an empty `traceId` variable [passed to the builder](https://github.com/openzipkin/zipkin-aws/blob/9bb5725f20f04e09efd626cebd039213820ca47b/brave-propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java#L187).

**Comment by codefromthecrypt** [comment]
thanks for the fixes in #203
