### ISSUE TITLE
Does'nt work with AWS SQS FIFO queue

### ISSUE THREAD

**Issue by raevilman** [openzipkin/zipkin-aws#62]
Zipkin SQSSender doesn't work with AWS SQS FIFO queue

Throws following exception in AsyncReporter at this.sender.sendSpans(nextMessage).execute(); 

com.amazonaws.services.sqs.model.AmazonSQSException: The request must contain the parameter MessageGroupId. (Service: AmazonSQS; Status Code: 400; Error Code: MissingParameter; Request ID: 82b6a6cc-c2e8-5905-b27e-f45be9c97ea0)

**Comment by devinsba** [comment]
Zipkin's data store and model is designed to handle out of order span delivery and the senders do not guarantee order, this would be a feature without a purpose due to these reasons.

**Comment by raevilman** [comment]
Totally agree with @devinsba 
We can ignore/close this with proper mention of not supporting FIFO queues in README
