### ISSUE TITLE
Deprecate sparkstreaming-stream-kinesis

### ISSUE THREAD

**Issue by devinsba** [openzipkin/zipkin-aws#78]
With `zipkin-sparkstreaming` moving to the attic, we should deprecate or move this modules like was just done for `zipkin-zookeeper` perhaps

thoughts @adriancole

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-aws/pull/74 is to remove it. will attic prior. good point

**Comment by adriancole** [comment]
https://github.com/openzipkin-attic/sparkstreaming-stream-kinesis done!
