### ISSUE TITLE
Sending "unknown" as segment name to X-Ray results in incorrect data displayed in the X-Ray UI

### ISSUE THREAD

**Issue by robyf** [openzipkin/zipkin-aws#87]
As part of https://github.com/openzipkin/zipkin-aws/pull/59 a check has been added that sends "unknown" as segment name to X-Ray when the received span doesn't have a remote service name. This solves the issue that X-Ray segments must have a name but creates issues on the X-Ray side, for example:
![selection_007](https://user-images.githubusercontent.com/1094791/40534469-cdb43bf8-600e-11e8-9434-c13308edeede.png)
in this case the "unknown" segment belongs to the security-gateway-aws service and not to the test-app and in the service map "unknown" services appear as dependencies:
![selection_008](https://user-images.githubusercontent.com/1094791/40534512-ef0b73c0-600e-11e8-95f1-4f8736db57b1.png)

**Comment by adriancole** [comment]
Thanks for all the help

closed via 07d46d2 for now and https://docs.google.com/document/d/1ZFg2SX2DUJFRE8MpodV9DL9uYgNHe-90PMQIb1DrY8k/edit#

we can revisit as experience gains or alternate approaches become possible. For example adjusters on the collector side and whatnot.
